apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuzzy-succotash-balance
  labels:
    app: fuzzy-succotash-balance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fuzzy-succotash-balance
  template:
    metadata:
      labels:
        app: fuzzy-succotash-balance
    spec:
      containers:
        - name: fuzzy-succotash-balance
          image: peterjbishop/fuzzy-succotash-balance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: PORT
              value: "8080"
            - name: GIN_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GIN_PORT
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: REFRESH_TOKEN_SECRET
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PSQL_USER
            - name: PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PSQL_PASSWORD
            - name: PSQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PSQL_DBNAME
            - name: PSQL_HOST
              value: "postgres"
            - name: PSQL_PORT
              value: "5432"
            - name: PSQL_SSLMODE
              value: "disable"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
